//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class branches
    {
        public int branch_id { get; set; }
        public string branch_name { get; set; }
        public int branch_organizer { get; set; }
        public int branch_city { get; set; }
        public string branch_street { get; set; }
        public string branch_home_number { get; set; }
        public string branch_phone_number { get; set; }
    
        public virtual cities cities { get; set; }
        public virtual organizers organizers { get; set; }
    }
}
