//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cruise_offers
    {
        public int cruise_offer_id { get; set; }
        public int cruise_offer_organizer { get; set; }
        public int cruise_offer_cruise { get; set; }
        public int cruise_offer_departure_port { get; set; }
        public System.DateTime cruise_offer_departure_date { get; set; }
        public System.TimeSpan cruise_offer_departure_time { get; set; }
        public int cruise_offer_ending_port { get; set; }
        public System.DateTime cruise_offer_ending_date { get; set; }
        public System.TimeSpan cruise_offer_ending_time { get; set; }
        public int cruise_offer_price { get; set; }
    
        public virtual cruises cruises { get; set; }
        public virtual ports ports { get; set; }
        public virtual ports ports1 { get; set; }
        public virtual organizers organizers { get; set; }
    }
}
