//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entyties
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airlines> airlines { get; set; }
        public virtual DbSet<airplane_models> airplane_models { get; set; }
        public virtual DbSet<airplanes> airplanes { get; set; }
        public virtual DbSet<airports> airports { get; set; }
        public virtual DbSet<branches> branches { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<cruise_offers> cruise_offers { get; set; }
        public virtual DbSet<cruises> cruises { get; set; }
        public virtual DbSet<flights> flights { get; set; }
        public virtual DbSet<food> food { get; set; }
        public virtual DbSet<hotels> hotels { get; set; }
        public virtual DbSet<operators> operators { get; set; }
        public virtual DbSet<organizers> organizers { get; set; }
        public virtual DbSet<ports> ports { get; set; }
        public virtual DbSet<ship_classes> ship_classes { get; set; }
        public virtual DbSet<ships> ships { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tour_offers> tour_offers { get; set; }
        public virtual DbSet<tours> tours { get; set; }
    }
}
