//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entyties
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_offers
    {
        public int tour_offer_id { get; set; }
        public int tour_offer_organizer { get; set; }
        public int tour_offer_tour { get; set; }
        public int tour_offer_flight { get; set; }
        public int tour_offer_return_flight { get; set; }
        public int tour_offer_price { get; set; }
    
        public virtual flights flights { get; set; }
        public virtual flights flights1 { get; set; }
        public virtual organizers organizers { get; set; }
        public virtual tours tours { get; set; }
    }
}
